sudo: required
dist: trusty

language: haxe

os:
  - linux
  
haxe:
  - "3.2.1"
    
install:
  - haxelib install travix
  - haxelib run travix install
  - haxelib git tink_unittest https://github.com/kevinresol/tink_unittest
  - npm install busboy 

script:
  - haxelib run travix node -lib tink_unittest
